# Custom targets that are not generated by devctl.

ENVTEST_K8S_VERSION ?= 1.35.0

# test-ci is the CircleCI entry point. It differs from `make test` in two
# ways: it skips -race (the architect orb runs with CGO_ENABLED=0 and -race
# requires cgo) and it provisions envtest binaries on the fly so the
# controller-runtime suites under internal/{controller/remoteapp,crdacceptance}
# can spin up an apiserver+etcd.
.PHONY: test-ci
test-ci: ## Runs go test with envtest binaries provisioned, no -race.
	@echo "====> $@"
	@go install sigs.k8s.io/controller-runtime/tools/setup-envtest@release-0.23
	KUBEBUILDER_ASSETS="$$($$(go env GOPATH)/bin/setup-envtest use $(ENVTEST_K8S_VERSION) -p path)" \
		go test -ldflags "$(LDFLAGS)" ./...
