version: 2.1

orbs:
  architect: giantswarm/architect@7.1.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: tunnelport
          path: ./cmd
          pre_test_target: generate
          test_target: test
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: "architect"
          name: push-to-registries
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - main

      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: push-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "tunnelport"
          requires:
            - push-to-registries
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - main
